/**
 * Runs a toolbar action before a pointer can transfer focus away from the
 * textarea. The compatibility click generated by that pointer is ignored;
 * keyboard and assistive-technology clicks (detail === 0) remain semantic.
 */
export function handleFocusPreservingPress(event, activate) {
  if (!event || typeof activate !== 'function') return false;

  if (event.type === 'pointerdown') {
    if (event.isPrimary === false) return false;
    if (typeof event.button === 'number' && event.button !== 0) return false;
    event.preventDefault?.();
    activate('pointer');
    return true;
  }

  if (event.type === 'click') {
    const pointerType = event.pointerType || event.nativeEvent?.pointerType || '';
    if (pointerType || Number(event.detail || 0) !== 0) return false;
    activate('semantic-click');
    return true;
  }

  return false;
}
